In [1]:
import pandas as pd
import sqlite3

In [2]:
df = pd.read_csv("train.csv")

In [4]:
conn = sqlite3.connect("memory")
df.to_sql("orders", conn, index = False, if_exists="replace")

9800

In [6]:
sql = """
    select * from orders
"""
res = pd.read_sql(sql, conn)
res

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [7]:
##Sales distribution by Category
sql = """
    select Category, sum(sales) as total_sales
    from orders
    group by Category
    order by total_sales desc
"""
res = pd.read_sql(sql, conn)
res

          Category  total_sales
0       Technology  827455.8730
1        Furniture  728658.5757
2  Office Supplies  705422.3340

In [ ]:
#Sales distribution by Product Name
sql = """
    select "Product Name", sum(Sales) as total_Sales
    from orders
    group by "Product Name"
    order by total_sales desc
"""
res = pd.read_sql(sql, conn)
res

                                           Product Name  total_Sales
0                 Canon imageCLASS 2200 Advanced Copier    61599.824
1     Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2     Cisco TelePresence System EX90 Videoconferenci...    22638.480
3          HON 5400 Series Task Chairs for Big and Tall    21870.576
4            GBC DocuBind TL300 Electric Binding System    19823.479
...                                                 ...          ...
1844                  Acme Serrated Blade Letter Opener        7.632
1845                                Grip Seal Envelopes        7.072
1846                                           Xerox 20        6.480
1847                                            Avery 5        5.760
1848  Eureka Disposable Bags for Sanitaire Vibra Gro...        1.624

[1849 rows x 2 columns]

In [12]:
#Sales distribution by region
sql = """
    select Region, sum(Sales) as total_Sales
    from orders
    group by Region
    order by total_sales desc
"""
res = pd.read_sql(sql, conn)
res

    Region  total_Sales
0     West  710219.6845
1     East  669518.7260
2  Central  492646.9132
3    South  389151.4590

In [24]:
#Sales distribution by region
sql = """
    select Region, sum(Sales) as total_Sales
    from orders
    group by Region
    order by total_sales desc
"""
res = pd.read_sql(sql, conn)
res

    Region  total_Sales
0     West  710219.6845
1     East  669518.7260
2  Central  492646.9132
3    South  389151.4590

In [13]:
#Most purchased Custiomers
sql = """
    select "Customer Name", sum(Sales) as total_spent
    from orders
    group by "Customer Name"
    order by total_spent desc
    limit 10
"""
res = pd.read_sql(sql, conn)
res

        Customer Name  total_spent
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

In [14]:
#Customer Distribution by US
sql = """
    select State, count(distinct "Customer ID") as total_customers
    from orders
    group by State
    order by total_customers desc
"""
res = pd.read_sql(sql, conn)
res

                   State  total_customers
0             California              570
1               New York              409
2                  Texas              367
3           Pennsylvania              255
4               Illinois              231
5             Washington              223
6                   Ohio              196
7                Florida              178
8         North Carolina              120
9               Virginia              107
10              Michigan              105
11               Arizona               99
12             Tennessee               84
13               Georgia               80
14              Colorado               74
15               Indiana               67
16         Massachusetts               62
17            New Jersey               58
18              Kentucky               56
19             Wisconsin               51
20                Oregon               50
21              Maryland               45
22              Delaware               43
23           Connecticut               43
24             Minnesota               42
25              Oklahoma               34
26               Alabama               34
27              Missouri               28
28              Arkansas               27
29                  Utah               26
30           Mississippi               25
31          Rhode Island               24
32                Nevada               23
33              Nebraska               23
34            New Mexico               22
35             Louisiana               20
36        South Carolina               19
37         New Hampshire               17
38                  Iowa               16
39                Kansas               14
40                 Idaho               11
41               Montana                8
42               Vermont                5
43          South Dakota                5
44  District of Columbia                4
45                 Maine                3
46         West Virginia                2
47          North Dakota                2
48               Wyoming                1

In [15]:
#Most commonly used shipping methods
sql = """
    select "Ship Mode", count(*) as total_orders
    from orders
    group by "Ship Mode"
    order by total_orders desc
"""
res = pd.read_sql(sql, conn)
res

        Ship Mode  total_orders
0  Standard Class          5859
1    Second Class          1902
2     First Class          1501
3        Same Day           538

In [16]:
#Difference between order date and shipping date
sql = """
    select avg("Ship Date" - "Order Date") as avg_shipping_days
    from orders
"""
res = pd.read_sql(sql, conn)
res

   avg_shipping_days
0            0.40898

In [18]:
#Number of requests per City
sql = """
    select City, count(*) as total_orders
    from orders
    group by City
    order by total_orders desc
    limit 10
"""
res = pd.read_sql(sql, conn)
res

            City  total_orders
0  New York City           891
1    Los Angeles           728
2   Philadelphia           532
3  San Francisco           500
4        Seattle           426
5        Houston           374
6        Chicago           308
7       Columbus           221
8      San Diego           170
9    Springfield           161